version: "3.8"

services:
  my-frontend:
    build: .
    container_name: react_frontend
    ports:
      - "3000:80"    # Nginx serves on 80 inside container
    networks:
      - hackstreet-net
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: always

networks:
  hackstreet-net:
    external: true
    name: hackstreet-net